version: '0.0.1'

services:
  backend:
    container_name: backend
    build: ./faur_backend/
    image: ulesrend-backend
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /src
    environment:
      - NODE_ENV=production
    command: node /dist/index.js
    networks:
      - ulesrend

  frontend:
    container_name: frontend
    build: ./faur_frontend/
    image: ulesrend-frontend
    ports:
      - 127.0.0.1:3001:3001
    working_dir: /asd
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    command: npm run start
    networks:
      - ulesrend

  database:
    container_name: postgres_database
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql
    networks:
      - ulesrend

volumes:
  db:
    name: postgres-database-data
    driver: local

networks:
  ulesrend:
    driver: bridge
